# Generated by Django 2.0.6 on 2018-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('register_plate', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=264)),
            ],
        ),
    ]
